// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "You":return img`
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f f f c c f f f c . 
f f f c f f f f f f f c . 
c c c f f f e e f f c c . 
f f f f f e e f f c c f . 
f f f b f e e f b f f f . 
. f 4 1 f 4 4 f 1 4 f . . 
. f e 4 4 4 4 4 4 e f . . 
. f f f e e e e f f f . . 
f e f 2 2 2 2 2 2 f e f . 
e 4 f 2 2 2 2 2 2 f 4 e . 
e e f 2 2 2 2 2 2 f e e . 
. . . 7 7 7 7 7 7 . . . . 
. . . 7 7 . . 7 7 . . . . 
`;
            case "image3":
            case "Soldier":return img`
......ffff..............
....fff88fff............
...fff8888fff...........
..fffeeeeeefff..........
..ffe888888eef..........
..fe8ffffff8ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f888888f1edde.......
fcf.f888888f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "King":return img`
........................
.....5..5..5............
.....5..5..5............
.....5552555............
......55555.............
.....ffffff.............
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....c55c.
.ffefbf44fbfeff...c55c..
.fee4dddddd4eef.cc55c...
f5feeddddd4eeffec55c....
f5ffee4444ee4fddccc.....
f5f4f888888f1edde.......
f5f.f888888f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image4":
            case "Treasure":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . c d 5 d c . . . . . 
. . . b c c d 5 5 5 d c c b . . 
. . b d d 5 5 5 5 5 5 5 d d b . 
. . . b c c d 5 5 5 d c c b . . 
. . . . . . c d 5 d c . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Soldier_Animation":
            case "anim2":return [img`
........................
.....ffff...............
...fff88fff.............
..fff8888fff............
.fffeeeeeefff...........
.ffe888888eef...........
.fe8ffffff8ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf8888f4e...........
fbbbbf8888fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
......ffff..............
....fff88fff............
...fff8888fff...........
..fffeeeeeefff..........
..ffe888888eef..........
..fe8ffffff8ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f8888edde...........
fcf.f88cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
`, img`
........................
........................
.......ff...............
.....ff88ff.............
...fff8888fff...........
..fff888888fff..........
..fff888888fff..........
..feeeeeeeeeeff.........
.ffe88888888eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef88888f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`, img`
......ffff..............
....fff88fff............
...fff8888fff...........
..fffeeeeeefff..........
..ffe888888eef..........
..fe8ffffff8ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f888888f1edde.......
fcf.f888888f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`];
            case "Treasure_Animation":
            case "anim3":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . c d 5 d c . . . . . 
. . . b c c d 5 5 5 d c c b . . 
. . b d d 5 5 5 5 5 5 5 d d b . 
. . . b c c d 5 5 5 d c c b . . 
. . . . . . c d 5 d c . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . b d b c . . . . . 
. . . . b b c 5 5 5 c b b . . . 
. . . . b 5 5 5 1 5 5 5 b . . . 
. . . c c 5 5 5 1 5 5 5 c c . . 
. . b b 5 5 5 1 1 1 5 5 5 b b . 
. . d d 5 1 1 1 1 1 1 1 5 d d . 
. . b b 5 5 5 1 1 1 5 5 5 b b . 
. . . c c 5 5 5 1 5 5 5 c c . . 
. . . . b 5 5 5 1 5 5 5 b . . . 
. . . . b b c 5 5 5 c b b . . . 
. . . . . . c b d b c . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . 1 . . . . . . . . . . 
. . 1 1 . . . 1 1 1 . . . . . . 
. . 1 1 . 1 1 1 1 1 1 1 . . . . 
. . . . 1 1 1 1 1 1 1 1 1 . . . 
. . . 1 1 1 1 1 1 1 1 1 1 1 . . 
. . . 1 1 1 1 1 1 1 1 1 1 1 . . 
. . 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. . 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. . 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. . . 1 1 1 1 1 1 1 1 1 1 1 . . 
. . . 1 1 1 1 1 1 1 1 1 1 1 . . 
. . . . 1 1 1 1 1 1 1 1 1 . . . 
. . 1 . . 1 1 1 1 1 1 1 . . . . 
. . . . . . . 1 1 1 . . . . 1 . 
. . . . . . . . . . . . . . . . 
`];
            case "WalkForward_You":
            case "anim4":return [img`
. . . . f f f f . . . . . 
. . f f c c c c f f . . . 
. f f c c c c c c f f . . 
f f c c c c c c c c f f . 
f f c c f c c c c c c f . 
f f f f f c c c f c c f . 
f f f f c c c f c c f f . 
f f f f f f f f f f f f . 
f f f f f f f f f f f f . 
. f f f f f f f f f f . . 
. f f f f f f f f f f . . 
f e f f f f f f f f e f . 
e 4 f 2 2 2 2 2 2 2 4 e . 
e e f 2 2 2 2 2 2 f e e . 
. . . 7 7 7 7 7 7 . . . . 
. . . 7 7 . . 7 7 . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . . f f f f . . . . 
. . . f f c c c c f f . . 
. f f f c c c c c c f f . 
f f c c c c c c c c c f f 
f c c c c f c c c c c c f 
. f f f f c c c c f c c f 
. f f f f c c f c c c f f 
. f f f f f f f f f f f f 
. f f f f f f f f f f f f 
. . f f f f f f f f f f . 
. . e f f f f f f f f f . 
. . e f f f f f f f f e f 
. . 4 2 2 2 2 2 2 e 4 4 e 
. . e 7 7 7 7 7 7 7 e e . 
. . . 7 7 7 . . . . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . . f f f f . . . . 
. . . f f c c c c f f . . 
. . f f c c c c c c f f . 
. f f f c c c c c c c f f 
f f f c c c c c c c c c f 
f f c c c f c c c c c c f 
. f f f f f c c c f c f f 
. f f f f c c f f c f f f 
. . f f f f f f f f f f f 
. . f f f f f f f f f f . 
. . f f f f f f f f f e . 
. f e f f f f f f f f e . 
. e 4 4 e 2 2 2 2 2 2 4 . 
. . e e 7 7 7 7 7 7 7 e . 
. . . . . . . . 7 7 7 . . 
`];
            case "WalkRight_You":
            case "anim5":return [img`
. . . . . . . . . . . . . 
. . . f f f f f f . . . . 
. f f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f c f f f c f f f . 
f c f f c c f f f c c f f 
f c c f f f f e f f f f f 
f f f f f f f e e f f f . 
f f e e f b f e e f f f . 
f f e 4 e 1 f 4 4 f f . . 
. f f f e 4 4 4 4 f . . . 
. 4 4 4 e e e e f f . . . 
. e 4 4 e 2 2 2 2 f . . . 
. f e e f 2 2 2 2 f f . . 
. f f f f f f f f f f . . 
. . f f . . . f f f . . . 
`, img`
. . . . . . . . . . . . . 
. . . f f f f f f . . . . 
. f f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f c f f f c f f f . 
f c f f c c f f f c c f f 
f c c f f f f e f f f f f 
f f f f f f f e e f f f . 
f f e e f b f e e f f . . 
. f e 4 e 1 f 4 4 f f . . 
. f f f e e 4 4 4 f . . . 
. . f e 4 4 e e f f . . . 
. . f e 4 4 e 2 2 f . . . 
. f f f e e f 2 2 f f . . 
. f f f f f f f f f f . . 
. . f f . . . f f f . . . 
`, img`
. . . f f f f f . . . . . 
. f f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f c f f f c f f . . 
f c f f c c f f f c c f f 
f c c f f f f e f f f f f 
f f f f f f f e e f f f . 
f f e e f b f e e f f . . 
. f e 4 e 1 f 4 4 f . . . 
. f f f e 4 4 4 4 f . . . 
. . f e e e e e f f . . . 
. . e 4 4 e 2 2 2 f . . . 
. . e 4 4 e 2 2 2 f . . . 
. . f e e f 2 2 2 f . . . 
. . . f f f f f f . . . . 
. . . . f f f . . . . . . 
`];
            case "WalkLeft_You":
            case "anim6":return [img`
. . . . . f f f f f . . . 
. . . f f f f f f f f f . 
. . f f f c f f f f f f . 
. . f f c f f f c f f f f 
f f c c f f f c c f f c f 
f f f f f e f f f f c c f 
. f f f e e f f f f f f f 
. . f f e e f b f e e f f 
. . . f 4 4 f 1 e 4 e f . 
. . . f 4 4 4 4 e f f f . 
. . . f f e e e e e f . . 
. . . f 2 2 2 e 4 4 e . . 
. . . f 2 2 2 e 4 4 e . . 
. . . f 2 2 2 f e e f . . 
. . . . f f f f f f . . . 
. . . . . . f f f . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . f f f f f f . . . 
. . . f f f f f f f f f . 
. . f f f c f f f f f f . 
. f f f c f f f c f f f f 
f f c c f f f c c f f c f 
f f f f f e f f f f c c f 
. f f f e e f f f f f f f 
. . f f e e f b f e e f f 
. . f f 4 4 f 1 e 4 e f . 
. . . f 4 4 4 e e f f f . 
. . . f f e e 4 4 e f . . 
. . . f 2 2 e 4 4 e f . . 
. . f f 2 2 f e e f f f . 
. . f f f f f f f f f f . 
. . . f f f . . . f f . . 
`, img`
. . . . . . . . . . . . . 
. . . . f f f f f f . . . 
. . . f f f f f f f f f . 
. . f f f c f f f f f f . 
. f f f c f f f c f f f f 
f f c c f f f c c f f c f 
f f f f f e f f f f c c f 
. f f f e e f f f f f f f 
. f f f e e f b f e e f f 
. . f f 4 4 f 1 e 4 e f f 
. . . f 4 4 4 4 e f f f . 
. . . f f e e e e 4 4 4 . 
. . . f 2 2 2 2 e 4 4 e . 
. . f f 2 2 2 2 f e e f . 
. . f f f f f f f f f f . 
. . . f f f . . . f f . . 
`];
            case "King_Animation":
            case "anim1":return [img`
........................
........................
...5...5...5............
...5...5...5............
...555525555............
....5555555.............
....ffffff..............
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
f5555f444eef............
f5555f8888f4e...........
f5555f8888fd4...........
.f55f45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
....5...5...5...........
....5...5...5...........
....555525555...........
.....5555555............
.....ffffff.............
..ffffeee69fff..........
.ffefbf49689eff.........
.fee41fd9896eef.........
f5feedddd96eff..........
f5ffee444edd4e..........
f5f4f8888edde...........
f5f.f88cccee............
.ff.f44c5c4f............
....fff55cff............
.....f55cff.............
....c55c................
....c5c.................
....cc..................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
....5...5...5...........
....5...5...5...........
....555525555...........
.....5555555............
.fffffeee99ffff.........
f5fefbf46686eff.........
f5fe41fd9869ef..........
f5ffe4ddd69efe..........
f5fef88888f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc5cc...........
.........c5c............
.........c5c............
.........c5c............
.........c5c............
`, img`
........................
.....5..5..5............
.....5..5..5............
.....5552555............
.....5555555............
.....ffffff.............
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....c55c.
.ffefbf44fbfeff...c55c..
.fee4dddddd4eef.cc55c...
f5feeddddd4eeffec55c....
f5ffee4444ee4fddccc.....
f5f4f888888f1edde.......
f5f.f888888f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`];
            case "WalkDown_You":
            case "anim7":return [img`
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f f f c c f f f c . 
f f f c f f f f f f f c . 
c c c f f f e e f f c c . 
f f f f f e e f f c c f . 
f f e b f 4 e f b f f f . 
. f e 1 f 4 4 f 1 4 f . . 
. f e 4 4 4 4 4 4 e f . . 
. f f f e e e e f f f . . 
f e f 2 2 2 2 2 2 f e f . 
e 4 f 2 2 2 2 2 2 f 4 e . 
e e f 2 2 2 2 2 2 f e e . 
. . . 7 7 7 7 7 7 . . . . 
. . . 7 7 . . 7 7 . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . . f f f f . . . . 
. . . f f f f f f f f . . 
. . f f f f f f c f f f . 
f f f f f f f c c f f f c 
f f f f c f f f f f f f c 
. c c c f f f e e f f c c 
. f f f f f e e f f c c f 
. f f e b f e e f b f f f 
. f f e 1 f 4 4 f 1 4 f f 
. . f e e e 4 4 4 e e f e 
. f e f 2 2 2 2 2 4 4 4 e 
. e 4 f 2 2 2 2 2 4 4 e . 
. . . f 2 2 2 2 2 e e . . 
. . . 7 7 7 7 7 7 7 . . . 
. . . 7 7 7 . . . . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f c f f f f f f . . 
c f f f c c f f f f f f f 
c f f f f f f f c f f f f 
c c f f e e f f f c c c . 
f c c f f e e f f f f f . 
f f f b f e e f b f f f . 
f f 4 1 f 4 4 f 1 4 f f . 
e f e e 4 4 4 4 4 e f . . 
e 4 4 4 2 2 2 2 2 f e f . 
. e 4 4 2 2 2 2 2 f 4 e . 
. . e e 2 2 2 2 2 f . . . 
. . . 7 7 7 7 7 7 7 . . . 
. . . . . . . 7 7 7 . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
